package com.eagleairug.onlinepayment.views.main;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.ProgressBar;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class BackupHomeUIDesign extends VerticalLayout {
	protected VerticalLayout contentHome;
	protected Button btnRegister;
	protected Button btnLogin;
	protected Button btnPayment;
	protected VerticalLayout cBookingRef;
	protected Button btnBookingRefCancel;
	protected Button btnBookingRefProceed;
	protected VerticalLayout cPaymentDetails;
	protected VerticalLayout topContent;
	protected VerticalLayout midContent;
	protected VerticalLayout uiContentHeader;
	protected HorizontalLayout uiContent;
	protected HorizontalLayout uiControls;
	protected Button btnDetailsBack;
	protected Button btnDetailsCancel;
	protected Button btnPayInitiate;
	protected VerticalLayout cPayProccessing;
	protected VerticalLayout topContent2;
	protected VerticalLayout midContent2;
	protected VerticalLayout uiContentHeader2;
	protected Label lbPayProccessState;
	protected Label lbPayProccessStateDesc;
	protected HorizontalLayout uiContent2;
	protected ProgressBar barPayProccessState;
	protected HorizontalLayout uiControls2;
	protected Button btnPayProccessingClose;
	protected Label footerYearSeparator;
	protected Label footerCurretYr;
	protected Label footerPlatformBoss;

	public BackupHomeUIDesign() {
		Design.read(this);
	}
}
