package com.eagleairug.onlinepayment.views.main;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class BookingRefenceUIDesign extends VerticalLayout {
	protected VerticalLayout contentPayment;
	protected Button btnPaymentCancel;
	protected Button btnPaymentProceed;

	public BookingRefenceUIDesign() {
		Design.read(this);
	}
}
