package com.eagleairug.onlinepayment.views.main;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class PaymentDetailsUIDesign extends VerticalLayout {
	protected VerticalLayout cPaymentDetails;
	protected VerticalLayout topContent;
	protected VerticalLayout midContent;
	protected VerticalLayout uiContentHeader;
	protected HorizontalLayout uiContent;
	protected HorizontalLayout uiControls;
	protected Button btnDetailsBack;
	protected Button btnDetailsCancel;
	protected Button btnPayInitiate;

	public PaymentDetailsUIDesign() {
		Design.read(this);
	}
}
